import mongoose from 'mongoose';

const tripSchema = new mongoose.Schema({
  source: {
    type: String,
    required: true
  },
  destination: {
    type: String,
    required: true
  },
  vehicle: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Vehicle',
    required: true
  },
  driver: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Driver',
    required: true
  },
  cargoWeight: {
    type: Number, // in kg
    required: true
  },
  plannedDistance: {
    type: Number, // in km
    required: true
  },
  status: {
    type: String,
    required: true,
    enum: ['Draft', 'Dispatched', 'Completed', 'Cancelled'],
    default: 'Draft'
  },
  fuelConsumed: {
    type: Number, // in liters, set upon completion
    default: 0
  },
  finalOdometer: {
    type: Number, // in km, set upon completion
  },
  revenue: {
    type: Number, // in $, revenue generated by the trip
    default: 0
  }
}, {
  timestamps: true
});

const Trip = mongoose.model('Trip', tripSchema);
export default Trip;
